### ISSUE TITLE
PRでmergeされたbranchを自動削除

### ISSUE THREAD

**Issue by Ueda-Yuto** [orchestra-canvas-tokyo/homepage#27]
**Is your feature request related to a problem? Please describe.**
mergeされたbranchは基本的に不要なので消したい．

**Describe the solution you'd like**
ここら辺でできそう．
Member権限だと設定ができなさそうなので，やるとなったらOwnerの方に設定いただきたいですmm
https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by horn553** [comment]
設定しました！
main、productionは削除されないようにrulesetを追加しています

この期にownerにも追加しちゃいますね！
